# Generated by Django 5.2.8 on 2025-12-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyevent',
            name='sensor_reading',
            field=models.ForeignKey(blank=True, help_text='The sensor reading that triggered this anomaly detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='crop_app.sensorreading'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['sensor_reading'], name='anomaly_eve_sensor__a09573_idx'),
        ),
    ]
